# H2
application.recommendations-db.url= jdbc:h2:file:./transaction

# PostgreSQL
spring.datasource.url= jdbc:postgresql://localhost:5432/dynamic_rules
spring.datasource.username= user
spring.datasource.password= 123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log= classpath:liquibase/changelog-master.yml

# Spring
spring.jpa.hibernate.ddl-auto= validate
springdoc.swagger-ui.path= /swagger-ui.html

# TelegramBot
telegram.bot.token= 7964215154:AAEk3YgDA3EDMPn2UI24S09pvcpQ9dfzN4M
telegram.bot.name= RecommendationsBankProductsBot

# Info
management.endpoints.web.exposure.include=info